# -*- coding: utf-8 -*-
"""Copy of Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19NgIfPKs2khemXb4DIYa1_H19lVV0O5E
"""

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
import gradio as gr
import warnings

warnings.filterwarnings("ignore")

# Load model
model_name = "google/gemma-2-2b-it"
token = "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"

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    token=token
).to(device)

tokenizer = AutoTokenizer.from_pretrained(
    model_name,
    token=token
)

# ===== Knowledge Base (basic disease info) =====
faq = {
    "diabetes": "Diabetes is a condition where blood sugar levels are too high. Common symptoms: excessive thirst, frequent urination, fatigue. Management: balanced diet, exercise, regular checkups. Please consult a doctor for medication.",
    "asthma": "Asthma is a chronic lung condition causing difficulty in breathing, wheezing, and coughing. Triggers include dust, smoke, and cold air. Management: avoid triggers, practice breathing exercises, consult a doctor.",
    "covid": "COVID-19 is caused by coronavirus. Symptoms: fever, cough, loss of smell/taste, breathing difficulty. Prevention: vaccination, masks, hygiene, distancing.",
    "malaria": "Malaria is spread by mosquito bites. Symptoms: high fever, chills, sweating. Prevention: mosquito nets, repellents. Please consult a doctor immediately.",
    "heart attack": "A heart attack happens when blood flow to the heart is blocked. Symptoms: chest pain, shortness of breath, sweating. It's an emergency — seek medical help immediately!",
    "flu": "Flu (influenza) causes fever, cough, sore throat, muscle aches, and fatigue. Prevention: good hygiene, fluids, rest.",
    "cold": "Common cold symptoms include runny nose, sneezing, sore throat, mild fever. Usually self-resolves with rest, hydration, and warm fluids."
}

# ===== System Prompt =====
system_prompt = (
    "You are a helpful health assistant. "
    "Answer clearly and politely with useful health information. "
    "Do NOT prescribe medicines or dosages. "
    "If unsure, say: 'I am not sure, please consult a doctor.'\n"
)

# Conversation memory
chat_history = [system_prompt]

def check_faq(user_input):
    """Check if user input matches FAQ keywords."""
    for key in faq:
        if key in user_input.lower():
            return faq[key]
    return None

def chatbot_response(user_input):
    global chat_history

    # Step 1: Check FAQ first
    faq_answer = check_faq(user_input)
    if faq_answer:
        chat_history.append(f"User: {user_input}")
        chat_history.append(f"Assistant: {faq_answer}")
        return faq_answer

    # Step 2: Use LLM if not in FAQ
    chat_history.append(f"User: {user_input}")
    prompt = "\n".join(chat_history) + "\nAssistant:"

    inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=1024).to(device)

    outputs = model.generate(
        **inputs,
        max_new_tokens=200,
        temperature=0.8,
        top_p=0.9,
        do_sample=True
    )

    bot_reply = tokenizer.decode(outputs[0], skip_special_tokens=True)

    # Extract assistant’s reply
    if "Assistant:" in bot_reply:
        bot_reply = bot_reply.split("Assistant:")[-1].strip()

    if bot_reply.strip() == "":
        bot_reply = "I am not sure, please consult a doctor."

    chat_history.append(f"Assistant: {bot_reply}")
    return bot_reply


# ===== Gradio UI =====
def chatbot_interface(user_input, history):
    response = chatbot_response(user_input)
    history.append((user_input, response))
    return history, ""

demo = gr.Blocks()

with demo:
    gr.Markdown("## 🩺 Healthcare Chatbot")
    chatbot = gr.Chatbot(height=400)
    with gr.Row():
        user_input = gr.Textbox(placeholder="Ask me about health, diseases, or prevention...", lines=1)
        send_button = gr.Button("Send")

    history = gr.State([])

    send_button.click(chatbot_interface, inputs=[user_input, history], outputs=[chatbot, user_input])
    user_input.submit(chatbot_interface, inputs=[user_input, history], outputs=[chatbot, user_input])

demo.launch()